### ISSUE TITLE
Add visual indicator of Access-Token status on the top bar

### ISSUE THREAD

**Issue by jtschichold** [PaloAltoNetworks/apiexplorer#5]
* API Explorer version: ??
* Python version: 3.6u
* Operating System: RHEL

# Problem

With the current release of API Explorer, if the Access-Token has expired the first query you make in the session fails. This is a bit annoying as you have to interrupt your flow to go to the Authorize page and refresh.

# Suggestion

Please add a visual indicator on the top bar that signals to the user the expiration status of the Access-Token. It would be even better if that indicator was a button you can click to refresh if the token has expired.

**Comment by sserrata** [comment]
**Update**

* Will introduce `Credentials` class to API Explorer which will eliminate requirement for manual refresh or periodic refresh using a cronjob.

**Comment by sserrata** [comment]
Introduced support for `Credentials` in 90f8409b9da95c729dc9c9190eb80d5c5a1dd2ae
